version: '3.8'

services:
  mosquitto_ssl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mosquitto_ssl
    ports:
      - "8883:8883"  # Porta MQTT com TLS
    volumes:
      - mosquitto_certs:/etc/mosquitto/certs    # Certificados gerados e persistidos aqui
      - mosquitto_data:/var/lib/mosquitto       # Mensagens persistentes (opcional)
      - mosquitto_logs:/var/log/mosquitto       # Logs persistentes (opcional)
    restart: unless-stopped

volumes:
  mosquitto_certs:
  mosquitto_data:
  mosquitto_logs:
