# docker-compose.yml
# Docker Compose file to set up a Mosquitto MQTT server with SSL/TLS ONLY,
# including a service to generate certificates and a healthcheck for Mosquitto.

version: '3.8'

services:
  cert_generator:
    build:
      context: .
      dockerfile: Dockerfile.cert_generator
    container_name: cert_generator
    volumes:
      - "./mosquitto/certs:/app/certs"

  mosquitto:
    image: eclipse-mosquitto:2.0.15 
    container_name: mosquitto_ssl
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs:ro 
    restart: unless-stopped
    command: mosquitto -c /mosquitto/mosquitto.conf
    depends_on:
      - cert_generator
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 8883 --cafile /mosquitto/certs/ca.crt --cert /mosquitto/certs/healthcheck.crt --key /mosquitto/certs/healthcheck.key -t '$$SYS/broker/version' -C 1 -W 5"]
      interval: 10s       # How often to perform the check (every 10 seconds)
      timeout: 5s         # How long to wait for the command to complete (5 seconds)
      retries: 3          # How many times to retry before marking as unhealthy (3 retries)
      start_period: 30s   # Give the service 30 seconds to start up before applying health checks
